### ISSUE TITLE
How can I fix this error?

### ISSUE THREAD

**Issue by masllsam** [rbaron/catprinter#19]
(base) C:\Users\marce\catprinter>python printer.py test.jpg --devicename GB03
⏳ Applying Floyd-Steinberg dithering to image...
✅ Done.
✅ Read image: (512, 384) (h, w) pixels
✅ Generated BLE commands: 28803 bytes
⏳ Looking for a BLE device named GB03...
✅ Got it. Address: 91:24:97:5B:61:54: GB03
⏳ Connecting to 91:24:97:5B:61:54: GB03...
Traceback (most recent call last):
  File "C:\Users\marce\anaconda3\lib\asyncio\locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\marce\anaconda3\lib\asyncio\tasks.py", line 492, in wait_for
    fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\marce\catprinter\printer.py", line 66, in <module>
    main()
  File "C:\Users\marce\catprinter\printer.py", line 62, in main
    loop.run_until_complete(run_ble(data, args.devicename, logger))
  File "C:\Users\marce\anaconda3\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\marce\catprinter\catprinter\ble.py", line 36, in run_ble
    async with BleakClient(address) as client:
  File "C:\Users\marce\anaconda3\lib\site-packages\bleak\backends\client.py", line 61, in __aenter__
    await self.connect()
  File "C:\Users\marce\anaconda3\lib\site-packages\bleak\backends\winrt\client.py", line 219, in connect
    await asyncio.wait_for(event.wait(), timeout=timeout)
  File "C:\Users\marce\anaconda3\lib\asyncio\tasks.py", line 494, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

**Comment by masllsam** [comment]
1 of 5 times I can print, the other 4 times I get this error. Would appreciate the help.

**Comment by masllsam** [comment]
fixed with pip install asyncio

**Comment by marekzrostlik** [comment]
Im having the same issue. Have you figured it out? 

`(venv) user@rpi:~/catprinter $ python3 catprinter-main/print.py -b floyd-steinberg /home/user/im/P1110103.JPG
⏳ Applying Floyd-Steinberg dithering to image...
✅ Done.
✅ Read image: (288, 384) (h, w) pixels
✅ Generated BLE commands: 14390 bytes
⏳ Trying to auto-discover a printer...
✅ Got it. Address: 48:0F:57:36:96:1F: MXW01
⏳ Connecting to 48:0F:57:36:96:1F: MXW01...
Traceback (most recent call last):
  File "/usr/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/user/catprinter/venv/lib/python3.13/site-packages/dbus_next/aio/message_bus.py", line 305, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/catprinter/catprinter-main/print.py", line 83, in <module>
    main()
    ~~~~^^
  File "/home/user/catprinter/catprinter-main/print.py", line 79, in main
    asyncio.run(run_ble(data, device=args.device))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/asyncio/base_events.py", line 725, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/user/catprinter/catprinter-main/catprinter/ble.py", line 103, in run_ble
    async with BleakClient(address) as client:
               ~~~~~~~~~~~^^^^^^^^^
  File "/home/user/catprinter/venv/lib/python3.13/site-packages/bleak/backends/client.py", line 61, in __aenter__
    await self.connect()
  File "/home/user/catprinter/venv/lib/python3.13/site-packages/bleak/backends/bluezdbus/client.py", line 267, in connect
    reply = await asyncio.wait_for(
            ^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "/usr/lib/python3.13/asyncio/tasks.py", line 506, in wait_for
    async with timeouts.timeout(timeout):
               ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/timeouts.py", line 116, in __aexit__
    raise TimeoutError from exc_val
TimeoutError`
