### ISSUE TITLE
Halftone Encoding Algorithm is Broken

### ISSUE THREAD

**Issue by 8bitben** [rbaron/catprinter#37]
When using `'halftone'` algorithm for image encoding, a Python error is present:

```
⏳ Applying halftone dithering to image...
Traceback (most recent call last):
  File "/Projects/cat_printer_interface/catprinter/print-modified.py", line 80, in <module>
    custom()
  File "/Projects/cat_printer_interface/catprinter/print-modified.py", line 48, in custom
    data = cmds_print_img(bin_img, dark_mode=True)
  File "/Projects/cat_printer_interface/catprinter/catprinter/cmds.py", line 167, in cmds_print_img
    data += cmd_print_row(row)
  File "/Projects/cat_printer_interface/catprinter/catprinter/cmds.py", line 127, in cmd_print_row
    encoded_img = run_length_encode(img_row)
  File "/Projects/cat_printer_interface/catprinter/catprinter/cmds.py", line 101, in run_length_encode
    if val == last_val:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
✅ Done.
```

`$ python --version
Python 3.10.2
`

**Comment by rbaron** [comment]
Thanks for filing the issue @8bitben. I took a quick look and #38 should fix it.
