### ISSUE TITLE
Problem with preview: TypeError: ufunc 'invert' not supported for the input types

### ISSUE THREAD

**Issue by lachesis** [rbaron/catprinter#54]
```

$ python3 ./print.py -b none -s ~/cat.png
Traceback (most recent call last):
  File "/home/user/build/catprinter/./print.py", line 83, in <module>
    main()
  File "/home/user/build/catprinter/./print.py", line 69, in main
    show_preview(bin_img)
  File "/home/user/build/catprinter/catprinter/img.py", line 143, in show_preview
    preview_img = ~bin_img.astype(float)
TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
![cat](https://user-images.githubusercontent.com/347481/165838000-ce8d0a0b-2df2-42d1-b7a9-64e43a98ad01.png)

**Comment by rbaron** [comment]
Seems like the refactoring in #51 broke the preview. @akx could you please take a look?

**Comment by rbaron** [comment]
Actually I think that fixes it. Please let me know if it works for you @lachesis.

**Comment by akx** [comment]
Sorry, I've been away on holiday for a bit :) Should've realized the precedence works like that, glad you got it fixed.
