### ISSUE TITLE
Difficulties printing YHK model

### ISSUE THREAD

**Issue by venthewolf** [rbaron/catprinter#73]
I tried printing with this script.
It will connect to my printer but it errors out with the following error:

I'm using endeavourOS (arch linux) on a Dell Latitude E5450
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/bleak/backends/bluezdbus/client.py", line 209, in connect
    reply = await self._bus.call(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/dbus_fast/aio/message_bus.py", line 384, in call
    await future
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sven/Thermal printer/catprinter-main/print.py", line 83, in <module>
    main()
  File "/home/sven/Thermal printer/catprinter-main/print.py", line 79, in main
    asyncio.run(run_ble(data, device=args.device))
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/sven/Thermal printer/catprinter-main/catprinter/ble.py", line 80, in run_ble
    async with BleakClient(address) as client:
  File "/usr/lib/python3.12/site-packages/bleak/__init__.py", line 565, in __aenter__
    await self.connect()
  File "/usr/lib/python3.12/site-packages/bleak/__init__.py", line 605, in connect
    return await self._backend.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/bleak/backends/bluezdbus/client.py", line 146, in connect
    async with async_timeout(timeout):
  File "/usr/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    raise TimeoutError from exc_val
TimeoutError
```

**Comment by Betelgeuse93** [comment]
Hi, I've also a YHK model, that's my output:

``` 
./print.py --device YHK-572E unicorno.jpg 

⏳ Applying Floyd-Steinberg dithering to image...
✅ Done.
✅ Read image: (384, 384) (h, w) pixels
✅ Generated BLE commands: 17513 bytes
⏳ Looking for a BLE device named YHK-572E...
✅ Got it. Address: 24:00:40:00:57:2E: YHK-572E
⏳ Connecting to 24:00:40:00:57:2E: YHK-572E...
Traceback (most recent call last):
  File "/home/fabrizio/catprinter/./print.py", line 83, in <module>
    main()
    ~~~~^^
  File "/home/fabrizio/catprinter/./print.py", line 79, in main
    asyncio.run(run_ble(data, device=args.device))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3.13/asyncio/base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/fabrizio/catprinter/catprinter/ble.py", line 98, in run_ble
    async with BleakClient(address) as client:
               ~~~~~~~~~~~^^^^^^^^^
  File "/home/fabrizio/catprinter/venv/lib/python3.13/site-packages/bleak/backends/client.py", line 61, in __aenter__
    await self.connect()
  File "/home/fabrizio/catprinter/venv/lib/python3.13/site-packages/bleak/backends/bluezdbus/client.py", line 278, in connect
    assert_reply(reply)
    ~~~~~~~~~~~~^^^^^^^
  File "/home/fabrizio/catprinter/venv/lib/python3.13/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.NotAvailable] br-connection-profile-unavailable
```
