### ISSUE TITLE
Troublesooting bluez error

### ISSUE THREAD

**Issue by samthelion17** [rbaron/catprinter#74]
I get this everytime I try to print:
```shell
⏳ Applying Floyd-Steinberg dithering to image...
✅ Done.
✅ Read image: (288, 384) (h, w) pixels
✅ Generated BLE commands: 11085 bytes
⏳ Connecting to 69:CE:2A:FF:B5:2A...
Traceback (most recent call last):
  File "/home/samthelion17/Desktop/catprinter/./print.py", line 83, in <module>
    main()
  File "/home/samthelion17/Desktop/catprinter/./print.py", line 79, in main
    asyncio.run(run_ble(data, device=args.device))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/samthelion17/Desktop/catprinter/catprinter/ble.py", line 80, in run_ble
    async with BleakClient(address) as client:
  File "/home/samthelion17/Desktop/catprinter/venv/lib/python3.10/site-packages/bleak/backends/client.py", line 61, in __aenter__
    await self.connect()
  File "/home/samthelion17/Desktop/catprinter/venv/lib/python3.10/site-packages/bleak/backends/bluezdbus/client.py", line 278, in connect
    assert_reply(reply)
  File "/home/samthelion17/Desktop/catprinter/venv/lib/python3.10/site-packages/bleak/backends/bluezdbus/utils.py", line 23, in assert_reply
    raise BleakDBusError(reply.error_name, reply.body)
bleak.exc.BleakDBusError: [org.bluez.Error.NotAvailable] br-connection-profile-unavailable
```
My device looks exactly like yours but it's called SC03h-CE69, It is NOT recognized when I connect it via USB (I know some of these printers do get recognized)

**Comment by mariunaise** [comment]
Have you found a solution for this problem? 
I have a similar device called SC03-80B9 and get the same error.

**Comment by samthelion17** [comment]
> Have you found a solution for this problem? I have a similar device called SC03-80B9 and get the same error.

Not really, I gave my cat printer away I got myself the M02, and it works as expected.
